language: java
jdk:
  - oraclejdk8

sudo: required
install: true

cache:
 directories:
 - '$HOME/.m2/repository'

script:
- mvn clean test -Pjacoco coveralls:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
